name: wake up heroku at morning
on:
  schedule:
    # - cron: "30 07 * * *"
    - cron: "* * * * *"
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: call heroku
        run: curl ${{ secrets.HEROKU_URL }}
