name: Wake Up Heroku
on:
  schedule:
    # - cron: "30 23 * * *"
    - cron: "*/5 * * * *"
jobs:
  WakeUp-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: call heroku
        run: curl  ${{ secrets.HEROKU_URL }}
