name: Wake Up Heroku
on:
  schedule:
    # - cron: "30 23 * * *"
    - cron: "* * * * *"
jobs:
  WakeUp-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: call heroku
        env:
          HEROKUURL: ${{ secrets.HEROKUURL }}
        run: curl ${{ env.HEROKUURL }}
