name: Wake Up
on:
  schedule:
    # - cron: "30 07 * * *"
    - cron: "* * * * *"
jobs:
  WakeUp-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: call heroku
        run: curl https://gogopowerkimibot.herokuapp.com
